---
name: 🚀 功能请求
description: 建议新功能或改进
title: "[Feature]: "
labels: [enhancement, needs-triage]
assignees:
  - gandli
body:
  - type: markdown
    attributes:
      value: |
        感谢您的建议！请填写以下信息以帮助我们了解您的需求。

  - type: dropdown
    id: request_type
    attributes:
      label: 请求类型
      description: 选择最符合的请求类型
      options:
        - 添加新的 Cask
        - 改进现有 Cask
        - 工作流优化
        - 文档改进
        - 脚本功能增强
        - 其他
    validations:
      required: true

  - type: input
    id: app_name
    attributes:
      label: 应用名称
      description: 如果是添加新 Cask，请提供应用名称
      placeholder: "例如: MyAwesomeApp"

  - type: input
    id: app_homepage
    attributes:
      label: 应用官网
      description: 应用的官方网站或 GitHub 仓库
      placeholder: https://github.com/owner/repo 或 https://example.com

  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 详细描述您希望添加或改进的功能
      placeholder: |
        请详细描述：
        1. 您希望实现什么功能？
        2. 这个功能如何帮助用户？
        3. 您期望的实现方式是什么？
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 动机和用例
      description: 解释为什么需要这个功能
      placeholder: |
        - 当前的痛点是什么？
        - 这个功能将解决什么问题？
        - 有多少用户可能受益？
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您是否考虑过其他解决方案？
      placeholder: |
        - 是否有其他方式实现相同目标？
        - 为什么选择这种方案？
        - 是否有类似的实现可以参考？

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 您认为这个功能的优先级如何？
      options:
        - 低 - 有时间的时候实现
        - 中 - 希望在未来几个月内实现
        - 高 - 希望尽快实现
        - 紧急 - 阻塞了重要功能
    validations:
      required: true

  - type: checkboxes
    id: app_requirements
    attributes:
      label: 应用要求（仅适用于新 Cask）
      description: 如果是添加新应用，请确认以下要求
      options:
        - label: 应用是免费的或有免费版本
        - label: 应用支持 macOS
        - label: 应用有稳定的下载链接
        - label: 应用不违反任何法律法规
        - label: 应用不是恶意软件

  - type: textarea
    id: additional_info
    attributes:
      label: 额外信息
      description: 任何其他相关信息
      placeholder: |
        - 相关链接或文档
        - 技术细节
        - 实现建议
        - 截图或示例

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献意愿
      description: 您是否愿意参与实现这个功能？
      options:
        - label: 我愿意提交 Pull Request 来实现这个功能
        - label: 我可以提供测试和反馈
        - label: 我可以提供技术指导或建议
        - label: 我只是提出建议，无法参与实现

  - type: checkboxes
    id: terms
    attributes:
      label: 确认
      description: 请确认您已经完成以下检查
      options:
        - label: 我已经搜索了现有的 Issues，确认这不是重复请求
          required: true
        - label: 我已经查看了项目文档和现有功能
          required: true
        - label: 这个请求符合项目的目标和范围
          required: true
        - label: 我提供的信息准确完整
          required: true
