name: Auto Update Casks

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨 3 点 UTC 执行

jobs:
  bump-casks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Generate Cask List
        id: casklist
        run: |
          CASKS=$(find Casks -type f -name "*.rb" -exec basename {} .rb \; | tr '\n' ' ')
          echo "casks=$CASKS" >> $GITHUB_OUTPUT

      - name: Bump Casks
        uses: Homebrew/actions/bump-packages@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          casks: ${{ steps.casklist.outputs.casks }}
          fork: false

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add Casks/
            git commit -m "Auto update casks"
            git push origin HEAD
          else
            echo "No changes to commit."
          fi
