name: Auto Update Casks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨 3 点 UTC 运行

jobs:
  bump-casks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Bump Casks
        uses: Homebrew/actions/bump-packages@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          # 指定只更新自建 Tap 下的 Casks 目录内容
          casks: |
            $(find Casks -type f -name "*.rb" -exec basename {} .rb \;)
          fork: false

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add Casks/
            git commit -m "Auto update casks"
            git push origin HEAD
          else
            echo "No changes to commit."
          fi
