name: Auto Update Casks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 每天凌晨 3 点 UTC 运行，可改为本地时间对应时区

jobs:
  bump-casks:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: List all casks
        id: list
        run: |
          echo "casks<<EOF" >> $GITHUB_OUTPUT
          find Casks -type f -name "*.rb" \
            | sed 's|Casks/||;s|.rb$||' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Bump all casks
        uses: Homebrew/actions/bump-packages@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          casks: ${{ steps.list.outputs.casks }}
          fork: false
