name: Auto Update Casks (Direct Commit)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 每天凌晨 3 点 UTC 执行

jobs:
  bump-casks:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: List all casks
        id: list
        run: |
          echo "casks<<EOF" >> $GITHUB_OUTPUT
          find Casks -type f -name "*.rb" \
            | sed 's|Casks/||;s|.rb$||' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Bump all casks (commit directly)
        env:
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "${{ steps.list.outputs.casks }}" | while read cask; do
            [[ -z "$cask" ]] && continue
            echo "Updating $cask ..."
            brew bump-cask-pr "$cask" --write-only --no-audit || true
          done

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Casks
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update Casks ($(date -u +'%Y-%m-%d'))"
            git push
          else
            echo "No updates found."
          fi
