name: Auto Update Casks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # 每 6 小时执行一次

permissions:
  contents: write

jobs:
  bump-casks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Update Homebrew
        run: brew update-reset

      - name: Update all Casks in Tap
        run: |
          set -eux
          brew tap-new gandli/proxy || true
          brew tap gandli/proxy https://github.com/gandli/homebrew-proxy
          cd "$(brew --repo gandli/proxy)/Casks"

          for cask in *.rb; do
            echo "Checking $cask ..."
            if grep -qE 'no_autobump!|livecheck do.*skip' "$cask"; then
              echo "Skipping $cask (autobump disabled)"
              continue
            fi

            if brew livecheck --cask "gandli/proxy/$cask" | grep -q "Newer version available"; then
              echo "Updating $cask ..."
              brew bump-cask-pr --write-only --commit --no-audit --no-style "gandli/proxy/$cask" || true
            fi
          done

      - name: Commit and push changes
        run: |
          cd "$(brew --repo ${{ github.repository }})"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-update casks"
            git push origin HEAD
          else
            echo "No updates found."
          fi
